### ISSUE TITLE
Searching on Virus Share

### ISSUE THREAD

**Issue by Beercow** [AdamGreenhill/VirusShare-Search#1]
You have to set up an account ond log in to search on Virus Share.

**Comment by AdamGreenhill** [comment]
What do you mean? You can download files containing all the hashes, and search them locally without logging in. You do however have to login to download the samples.

**Comment by Beercow** [comment]
What I ment was, you can search the Virushare site after you login without having to download the hash list. Notice the search box in the image. 
![image](https://cloud.githubusercontent.com/assets/10360919/13383948/0297b080-de56-11e5-94fd-42b71a4a4d17.jpeg)

**Comment by AdamGreenhill** [comment]
This script will download the hash files (located here: https://virusshare.com/hashes.4n6) which are accessible without logging in. The reason why it needs to be done this way is because the search bar accessible after logging into the site does not determine what collection file contains a specific sample.
